redis:
  hostname: "redis"
  port: 6379
  job_queue: "ranges"
  success_queue: "succeeded"
  failed_queue: "failed"
  progress_queue: "in_progress"
  metrics: "metrics"
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"

worker:
  stellar_core_image: "stellar/stellar-core:latest"
  replicas: 5
  resources:
    requests:
      cpu: "250m"
      memory: "1200Mi"
      ephemeral_storage: "35Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
      ephemeral_storage: "40Gi"

monitor:
  ingress_class_name: "private"
  hostname: "ssc-job-monitor.services.stellar-ops.com"
  logging_interval_seconds: 30
  logging_level: "INFO" # 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"

range_generator:
  strategy: "uniform" # "uniform" or "logarithmic"
  params:
    starting_ledger: 0
    latest_ledger_num: 100000
    overlap_ledgers: 320
    uniform_ledgers_per_job: 16000 # only for strategy="uniform"
    logarithmic_floor_ledgers: 16000 # only for strategy="logarithmic"
